### ISSUE TITLE
getFeed Issue

### ISSUE THREAD

**Issue by ErAmar** [double-break/spapi-php#48]
Exception when calling apiInstance->getFeeds: Client error: `GET https://sellingpartnerapi-eu.amazon.com/feeds/2021-06-30/feeds?feedTypes%5B0%5D=JSON_LISTINGS_FEED&marketplaceIds%5B0%5D=XXXXXXXXX&processingStatuses%5B0%5D=IN_PROGRESS&pageSize=10&createdSince=2022-01-21T11%3A37%3A23.000Z&createdUntil=2022-01-22T12%3A37%3A29.000Z` resulted in a `400 Bad Request` response:
{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "One or more required parameters missing",
      "d (truncated...)

**Comment by lyubo-slavilov** [comment]
> One or more required parameters missing

Yeah, this error is confusing enough, since this request do not have any required fields as described in the [official docs](https://developer-docs.amazon.com/sp-api/docs/feeds-api-v2021-06-30-reference#getfeeds)

I think your problem is with your actual query. it seems you are passing `feedTypes[]` and `marketplaceIds[]` and `processingStatuses[]` as a HTTP query parameters.
You should drop the `[]` and pass `feedTypes`, `marketplaceIds`, and `processingStatuses`. 
If you need to provide more than one value you need to use CSV to these query params.

Can you provide example code?
