### ISSUE TITLE
The request signature we calculated does not match the signature you provided.

### ISSUE THREAD

**Issue by cesarelasorella** [double-break/spapi-php#5]
Hi @lyubo-slavilov ,
I'm trying to use your library but I have a problem when I make a GET on **https://sellingpartnerapi-eu.amazon.com/products/pricing/v0/price**.
The response is _`403 Forbidden` response: { "errors": [ { "message": "The request signature we calculated does not match the signature you provided. C (truncated...).

Could you help me?

**Comment by lyubo-slavilov** [comment]
Hi @cesarelasorella , It would be helpful to see example of your code in order to reproduce the problem.
Here are some question that came to my mind and some  things you should check:
1. Did you setup your AWS IAM role and user according the official documentation?
2. Did you request all permissions for your application in developers central section in Amazon market interface?
3. Is there other endpoints which are working?
4. What version of the composer package you are using currently?

The error you are mensioning suggest one of two thing:
1. There is a problem with your Access tokens
2. There is a problem with the library

I'll do some tests to verify this particular call is working as expected and get back to you ASAP.

**Comment by lyubo-slavilov** [comment]
This issue is probably related to the strange format of `MarketplaceIds`. See this: https://github.com/double-break/spapi-php/issues/6#issuecomment-758729523 comment of another reporter.
